language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
    - python: 2.7
      env: PY=2.5
    - python: 2.7
      env: PY=3.1

install:
  - bash test/travis_setup.sh

script: python${PY:-} test/all.py fast

notifications:
  irc: "irc.freenode.org#pyneuronjs"
  on_success: "never"